### ISSUE TITLE
godef can't work

### ISSUE THREAD

**Issue by abin1989** [rogpeppe/godef#116]
My go source file:

package main

import (
	"fmt"
)

func main() {
	fmt.Println(111)
}

I exec "godef -debug -f main.go fmt.Println" in my shell.
Debug Info:
2019/04/26 11:10:14 exprType tuple:false pkg: *ast.SelectorExpr fmt.Println [
2019/04/26 11:10:14 exprType tuple:false pkg: *ast.Ident fmt [
2019/04/26 11:10:14 exprType tuple:false pkg: *ast.ImportSpec "fmt" [
2019/04/26 11:10:14 ] -> 0x0, Type{package "" *ast.ImportSpec "fmt"}
2019/04/26 11:10:14 ] -> 0xc0000206e0, Type{package "" *ast.ImportSpec "fmt"}
2019/04/26 11:10:14 member Type{package "" *ast.ImportSpec "fmt"} 'Println' {
2019/04/26 11:10:14 } -> &{func Println 0xc0006de180 <nil> <nil>}
2019/04/26 11:10:14 exprType tuple:false pkg: *ast.Ident Println [
2019/04/26 11:10:14 exprType tuple:false pkg: *ast.FuncType func(a ...interface{}) (n int, err error) [
2019/04/26 11:10:14 ] -> 0x0, Type{type "" *ast.FuncType func(a ...interface{}) (n int, err error)}
2019/04/26 11:10:14 ] -> 0xc0006d8910, Type{func "" *ast.FuncType func(a ...interface{}) (n int, err error)}
2019/04/26 11:10:14 ] -> 0xc0006d8910, Type{func "fmt" *ast.FuncType func(a ...interface{}) (n int, err error)}
/usr/local/Cellar/go/1.12.4/libexec/src/fmt/print.go:274:6

It's like godef is ok,but when I use nvim to open the go source file , put cursor on the word "Println",  then I try to ":GoDef" an gd,there is nothing happened.

**Comment by Yuanxiangz** [comment]
I have the same problem. "godef debug" works but cursor don't move

**Comment by shengdoushi** [comment]
It's nvim plugin's bug.
