### ISSUE TITLE
internal error: nil Pkg importing "errors" from "mypkg"

### ISSUE THREAD

**Issue by kevinburkemeter** [rogpeppe/godef#118]
I can only reproduce this with a "package main" Go binary in the same directory as go.mod - if I have a main that's nested several directories under go.mod, I can't reproduce. I also can't reproduce in libraries.

Steps to reproduce:

- Clone https://github.com/jmhodges/justrun - I put it in GOPATH but I don't think it matters.
- Configure vim-go at tip (2aa7c9d00af14ae71fdfe46f6a52b0a4f0fac774)
- configure x/tools at tip (ed542cd5b28ad1b474f8ff7ca112cad2c3ac2dc8), golang/go at tip (93a601dd2a)

Run

```
godef -f=$GOPATH/src/github.com/jmhodges/justrun/watch.go '-o=504' '-t'
```

I get the following error:

```
2019/10/22 09:35:08 internal error: nil Pkg importing "errors" from "github.com/jmhodges/justrun"
```

**Comment by hyangah** [comment]
Maybe dup of https://github.com/golang/go/issues/33554 which can be fixes with updating x/tools dependency.

**Comment by hus787** [comment]
had to use the following to fix the problem

`go get -v github.com/rogpeppe/godef@master`

**Comment by hyangah** [comment]
v1.1.2 is released. Thanks @rogpeppe !
