### ISSUE TITLE
godef: could not parse GOARCH and Go compiler 

### ISSUE THREAD

**Issue by guidao** [rogpeppe/godef#119]
When GO111MODULE=on, i can't goto definition in consul sdk. 

error message:
`
godef: could not parse GOARCH and Go compiler in format "<GOARCH> <compiler>" from stdout of go command:
`

Dependent libraries:
- https://github.com/hashicorp/consul

**Comment by jiacai2050** [comment]
It seems godef isn't compatible with modules, I migrate to gopls and everything is fine but have a similar issue
- https://github.com/golang/go/issues/35485

**Comment by guidao** [comment]
I use lsp-find-definition instead of godef. It's work.
