### ISSUE TITLE
Cannot jump to definition of instance methods

### ISSUE THREAD

**Issue by aaronkavlie-wf** [rogpeppe/godef#12]
godef does not seem to support jumping to the definition of an instance method.

Given this example:

```go
package main

import "fmt"

type foo struct{}

func (f *foo) Public() string {
	return "I am a method on foo"
}

func main() {
	f := &foo{}
	fmt.Println(f.Public())
}
```

```
$ godef -f ./godef_bug.go 'foo.Public'
./godef_bug.go:7:15

$ godef -f ./godef_bug.go 'f.Public'
godef: no declaration found for f.Public
```

in practice, I'm using godef in go-plus in atom, and it's always attempting lookup on an instance.

**Comment by IvanMalison** [comment]
This works in other editors, so it is probably an issue with the atom implementation.

**Comment by rogpeppe** [comment]
In your second godef call, the expression has no context, so "f" has no variable to resolve to, so it cannot work. If you passed it the file offset of the Public symbol inside main, then it should work.

**Comment by rogpeppe** [comment]
Closing as invalid.
