### ISSUE TITLE
Update code.google.com page to tell users about moving to github

### ISSUE THREAD

**Issue by diddledan** [rogpeppe/godef#15]
There is no mention on https://code.google.com/p/rog-go about the move to GitHub. As it stands there are many links on the www that point to the old location and users finding themselves there have no way of knowing where the project is or will be in the future now that google code hosting is plastering project pages with announcements about the end being neigh.

**Comment by rogpeppe** [comment]
Unfortunately that's not possible now that code.google.com is read-only.
