### ISSUE TITLE
Error with github.com/bugsnag/bugsnag-go

### ISSUE THREAD

**Issue by tobstarr** [rogpeppe/godef#2]
As already discussed here:
https://github.com/bugsnag/bugsnag-go/issues/14#issuecomment-73591827

Also with the modified command I get this error:

  $ ~/src/github.com/bugsnag/bugsnag-go o godef -t -debug -f ./doc.go Configure
  2015/02/09 22:21:31 exprType tuple:false pkg: *ast.Ident Configure [
  2015/02/09 22:21:31 ] -> 0x0, Type{bad "" <nil> }
  godef: no declaration found for Configure

Thank you

**Comment by tobstarr** [comment]
@rogpeppe any news here?

**Comment by rogpeppe** [comment]
Fixed by PR #22.
