### ISSUE TITLE
"9fans.net/go/acme" Inaccessible

### ISSUE THREAD

**Issue by bomoer** [rogpeppe/godef#23]
"9fans.net/go/acme" Inaccessible

**Comment by juliuskovac** [comment]
I would like to ask if it can be considered to remove dependency on "9fans.net/go/acme". It seems to be required only by acme.go file (which I assume is some support for acme editor - correct me if I am wrong). It cause download of about 1MB package (9fans.net/go) which I assume most of the users don't need. Its also go against singe responsibility principle.

**Comment by lukehoban** [comment]
Unsure if it's the same issue, but certificates for https://9fans.net appear to be expired, so it is no longer possible to `go get github.com/rogpeppe/godef`.

Reported here: https://github.com/9fans/go/issues/12.

But also another reminder that it would be nice to have `acme` dependency be separated out.

**Comment by rogpeppe** [comment]
Fixed by #35
