### ISSUE TITLE
godef: no declaration found for fmt.Println

### ISSUE THREAD

**Issue by hjolin** [rogpeppe/godef#31]
I am using Emacs go-mode with godef, but M-x godef can't find declarations in golang standard packages while it works for third party packages in $GOPATH, what am I doing wrong ?

**Comment by rogpeppe** [comment]
What version of Go are you using? Try rebuilding godef to see if it makes a
difference.

**Comment by hjolin** [comment]
yes, I rebuilt godef and it works now, thank you.

**Comment by NormanOu** [comment]
I met this problem too. Finally I found this issue, and it solves my problem too.
