### ISSUE TITLE
Does godef support relative import path?

### ISSUE THREAD

**Issue by hjolin** [rogpeppe/godef#32]
When I run 
`echo 'package foo; import "./httpproxy"; func main() { httpproxy.ListenTCP() }' | godef -i -o 60`
in command line, I get **parseLocalPackage error: no more package files found
godef: no declaration found for httpproxy.ListenTCP** error, and I am sure that httpproxy.ListenTCP is defined in a file inside ./httpproxy directory, so isn't relative import path supported?

**Comment by rogpeppe** [comment]
Relative import paths aren't supported in Go source files in general, I'm afraid.
