### ISSUE TITLE
godef returns error for mux.Vars or anything else from gorilla/mux

### ISSUE THREAD

**Issue by DmitriyMV** [rogpeppe/godef#48]
Quoting from another issue:

While debugging, I found that on hover over mux.Router, godef returns an error `godef: no declaration found for mux.Router`

https://github.com/Microsoft/vscode-go/issues/515

**Comment by ramya-rao-a** [comment]
Same thing happens to anything from the `net` package.

**Comment by astef** [comment]
Command which reproduces the problem:
`echo 'package foo; import "golang.org/x/net/context"; func fn() { context.Background() }' | godef -i -o 70`

Result:

> parseLocalPackage error: no more package files found
> godef: no declaration found for context.Background

**Comment by rogpeppe** [comment]
I can't reproduce this - is this still an issue?
If so, please provide a full Go program that demonstrates it.
The above snippet works OK for me.

**Comment by astef** [comment]
Sorry, I can't help with this now.
