### ISSUE TITLE
godef not working with type alias

### ISSUE THREAD

**Issue by ipfans** [rogpeppe/godef#71]
When I use type alias with golang 1.9, I got error:

```
godef -t -i -f source.go -o 121
godef: no identifier found
```
source file:
```go
type RedisOption = redis.Options
```

Or error:

```
godef -t -i -f source.go -o 594
godef: no declaration found for pkg.RedisOption
```

**Comment by ssoroka** [comment]
I see at least 1 other person has [tried to fix this](https://github.com/gofly/godef/commit/dbaf1ef0d083f34f15b86cd71b23f80621eecef3). I haven't had much luck with it. Maybe someone else could try it?
cc @rogpeppe

**Comment by lawrsp** [comment]
I found that because of the rewrite of some libs such as: ast, token, parser... it cannot support new language specifications.
Maybe using the original lib with golang package can solve these types of problems once for ever?

**Comment by xux1217** [comment]
Hey, I always meet this problem, and ijc's pr can't effect in my scene.

Problem source: https://github.com/libp2p/go-libp2p-examples
Use command: godef -debug -f libp2p-host/host.go libp2p.New

error:
src/github.com/libp2p/go-libp2p/libp2p.go:12:13: expected type, found '='

**Comment by cjqpker** [comment]
Has this problem solved now ?
