### ISSUE TITLE
cant find definition

### ISSUE THREAD

**Issue by Kurt-Shiwz** [rogpeppe/godef#84]
if import some lib like ". github.com/a/b", can't goto definition which define in b.
function is also undefined.
```
// b.go
type GlobalConfig struct {
	Localaddr string
}
func InitGlobalVars(globalconfig *GlobalConfig) error {
}


// main.go
import (
. github.com/a/b
)
// can't goto definition
globalconfig := &GlobalConfig{}
// InitGlobalVars is undefined
InitGlobalVars(globalconfig)
```

**Comment by boxu-zhang** [comment]
I've encountered such problem recently. And got it solved with two steps: 1, please make sure GOPATH & GOROOT environment variable are set properly. Some config might affect the variables value actually take effects, like 'go.gopath' setting of Vscode. 2, please make sure all of your source code are encoded without some BOM(UTF-8 BOM) or something like. 

Then it should work. @Kurt-Shiwz

**Comment by rogpeppe** [comment]
This is issue #19. The current answer is, I'm afraid: don't use dot-imports. They're never necessary.

**Comment by Kurt-Shiwz** [comment]
"Known limitations:

- it does not understand about "." imports
- it does not deal well with definitions in tests."
README write that.
@boxu-zhang
